---
version: "3"
services:
  ttynvt:
    container_name: ttynvt
    image: lansible/ttynvt:master
    command: -E -n ttyNVT0 -S 192.168.1.23:23
    read_only: true
    restart: always

  serial:
    container_name: serial
    image: alpine
    command: microcom -s 9600 /dev/ttyNVT0
