---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zwave-ttynvt
  labels:
    app: zwave-ttynvt
spec:
  selector:
    matchLabels:
      app: zwave-ttynvt
  template:
    metadata:
      labels:
        app: zwave-ttynvt
    spec:
      containers:
        - name: zwave-ttynvt
          image: lansible/ttynvt:master
          imagePullPolicy: Always
          args:
            - -n
            - ttyNVT0
            - -S
            - 192.168.1.23:23
          securityContext:
            # Needed to read the tty device on the host
            # Related: https://github.com/kubernetes/kubernetes/issues/60748
            privileged: true
            # Make container filesystem readonly
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: 100Mi
          volumeMounts:
            - name: cuse
              mountPath: /dev/cuse
      volumes:
        - name: cuse
          hostPath:
            path: /dev/cuse
            type: CharDevice
