---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ttynvt
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ttynvt
  labels:
    name: ttynvt
spec:
  selector:
    matchLabels:
      name: ttynvt
  template:
    metadata:
      labels:
        name: ttynvt
    serviceAccountName: ttynvt
    spec:
      containers:
      - name: ttynvt
        image: lansible/ttynvt:latest
        securityContext:
          # Needed to read the tty device on the host
          # Related: https://github.com/kubernetes/kubernetes/issues/60748
          privileged: true
          # Make container filesystem readonly
          readOnlyRootFilesystem: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: cuse
          mountPath: /dev/cuse
        # - name: dev
        #   mountPath: /dev
        #   readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: cuse
          hostPath:
            path: /dev/cuse
        # - name: dev
        #   hostPath:
        #     path: /dev
